### ISSUE TITLE
storybook module doesnot work!

### ISSUE THREAD

**Issue by sheecegardezi** [lazercaveman/nuxt3-starter#13]
Reproduce error:

```
yarn install
yarn storybook
```
Error:
```

ERR! import { logger } from '@storybook/node-logger';
ERR! ^^^^^^
ERR! 
ERR! SyntaxError: Cannot use import statement outside a module
..........
ERR! import { logger } from '@storybook/node-logger';
ERR! ^^^^^^
ERR! 
ERR! SyntaxError: Cannot use import statement outside a module
ERR!     at internalCompileFunction (node:internal/vm:73:18)
ERR!     at wrapSafe (node:internal/modules/cjs/loader:1176:20)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1218:27)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
ERR!     at Module._load (node:internal/modules/cjs/loader:958:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19)
ERR!     at require (node:internal/modules/cjs/helpers:110:18)
ERR!     at Object.<anonymous> (/home/sheece/Desktop/work/nuxt3-starter/node_modules/@storybook/addon-postcss/preset.js:1:18)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
...................
ℹ ｢wdm｣: wait until bundle finished: 
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
..........................
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

**Comment by lazercaveman** [comment]
cannot reproduce, doing `yarn install` + `yarn storybook` everything runs as it should be ...

**Comment by sheecegardezi** [comment]
@lazercaveman I think its the npm and node version on my system, Im installing nvm will downgrade and try again:

```
npm -v
9.5.0
$ node -v
v18.15.0
```

**Comment by lazercaveman** [comment]
> @lazercaveman I think its the npm and node version on my system, Im installing nvm will downgrade and try again:
> 
> ```
> npm -v
> 9.5.0
> $ node -v
> v18.15.0
> ```

I currently use Node v16.18.1, which works fine. The use of **Yarn Berry** should work without any problems (since this is the package manager I used and considered when setting up Nuxt-3-Starter). Using **npm** should work fine as well, if there appear problems with Pinia, you could  use `npm i --legacy-peer-deps` (which should solve the Pinia problems). 

There were some problems using some package managers with Nuxt 3 - but it looks to me like they are solved by now - for the sake of completeness here are the Thread-URLs anyway : )

- https://github.com/nuxt/framework/issues/581
- https://github.com/nuxt/framework/issues/5411
- https://github.com/nuxt/framework/discussions/3546

**Comment by sheecegardezi** [comment]
I updated `package.json`, i needed to add [openssl-legacy-provider](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported) options and [downgrade](https://github.com/storybookjs/storybook/issues/18727) storybook/addon-postcss

`yarn add -D @storybook/addon-postcss@2.0.0`

```
...
  "scripts":  {
...
    "storybook": "NODE_OPTIONS=--openssl-legacy-provider start-storybook -p 6006 -s ./public,./assets",
...
},
  "devDependencies": {
  ...
      "@storybook/addon-postcss": "2.0.0",
  ...
},
...
```
